import { DatabaseWriter } from "../_generated/server";
import { Id } from "../_generated/dataModel";
import { calculateStreakUpdate, applyStreakUpdate, dayDifference } from "./streakCalculation";
import { classifyPuzzle, isDailyPuzzle } from "./puzzleType";

/**
 * Streak Helpers - Database Operations for User Streaks
 *
 * Module: Shared database helpers for streak management
 * Location: convex/lib/ (not code-generated by Convex)
 *
 * CRITICAL BUSINESS RULE: Only updates streak for TODAY'S daily puzzle.
 * Archive/historical puzzle plays MUST NOT affect daily streak mechanics.
 *
 * DAY SEMANTICS: The puzzle's own date is the streak day marker. Chrondle's
 * canonical "today" is the player's local calendar day (the puzzle they play
 * is resolved by local date; see src/lib/time/dailyDate.ts), so the server
 * clock must never define the streak boundary — after 00:00 UTC a player's
 * daily puzzle date is one day behind the server's UTC date. Consecutive
 * puzzle dates are consecutive days by construction.
 *
 * Dependencies:
 * - streakCalculation: Pure functions for streak state management
 */

/**
 * Decide whether a puzzle play may touch the user's streak
 *
 * Pure decision function (exported for tests):
 * - "archive": puzzle date outside the timezone envelope (see puzzleType.ts)
 * - "older-than-last": puzzle dated before the user's last completion —
 *   playing backwards must never rewind or reset a streak
 * - "daily": streak update proceeds (calculateStreakUpdate owns the rest:
 *   same-day replay, consecutive-day increment, gap restart, loss reset)
 *
 * @param puzzleDate - ISO date (YYYY-MM-DD) of the puzzle being played
 * @param lastCompletedDate - User's last completion date or null
 * @param currentDate - Optional server date override (defaults to UTC now)
 */
export function shouldUpdateStreakForPuzzle(
  puzzleDate: string,
  lastCompletedDate: string | null,
  currentDate?: string,
): { update: boolean; reason: "daily" | "archive" | "older-than-last" } {
  const classification = classifyPuzzle(puzzleDate, currentDate);

  if (!isDailyPuzzle(classification)) {
    return { update: false, reason: "archive" };
  }

  if (lastCompletedDate && dayDifference(puzzleDate, lastCompletedDate) > 0) {
    return { update: false, reason: "older-than-last" };
  }

  return { update: true, reason: "daily" };
}

/**
 * Update user streak after completing a puzzle
 *
 * CRITICAL: Only updates streak for today's daily puzzle to prevent
 * archive/historical puzzle plays from affecting daily streak mechanics.
 *
 * @param ctx - Database writer context
 * @param userId - User ID to update
 * @param hasWon - Whether the user won the puzzle
 * @param puzzleDate - ISO date string (YYYY-MM-DD) of the puzzle being played
 */
export async function updateUserStreak(
  ctx: { db: DatabaseWriter },
  userId: Id<"users">,
  hasWon: boolean,
  puzzleDate: string,
) {
  const user = await ctx.db.get(userId);
  if (!user) {
    console.error("[updateUserStreak] User not found:", userId);
    throw new Error("User not found");
  }

  // CRITICAL: Only update streak for a daily puzzle (puzzle date within the
  // timezone envelope of the server's UTC day; see puzzleType.ts), and never
  // rewind: a play of an older-dated puzzle after a newer completion (e.g. a
  // UTC+14 player finishing tomorrow's puzzle, then replaying yesterday's
  // inside the envelope) must not reset or rewind the streak.
  const decision = shouldUpdateStreakForPuzzle(puzzleDate, user.lastCompletedDate || null);

  if (!decision.update) {
    console.warn("[updateUserStreak] Skipping streak update:", {
      reason: decision.reason,
      puzzleDate,
      lastCompletedDate: user.lastCompletedDate,
      userId,
    });
    return;
  }

  // Calculate streak update using explicit discriminated union.
  // The PUZZLE date — not the server clock — is the day marker: it is the
  // player's local "today" for daily play, and consecutive puzzle dates are
  // consecutive days by construction.
  const update = calculateStreakUpdate(
    user.lastCompletedDate || null,
    user.currentStreak,
    puzzleDate,
    hasWon,
  );

  // Log update for debugging
  console.warn("[updateUserStreak] Calculated update:", {
    userId,
    updateType: update.type,
    reason: update.reason,
    currentStreak: user.currentStreak,
  });

  // Handle no-change case explicitly (same-day replay)
  if (update.type === "no-change") {
    console.warn("[updateUserStreak] Same-day replay - preserving streak:", user.currentStreak);
    return; // No database update needed
  }

  // Apply the update to get new state
  const newState = applyStreakUpdate(
    {
      currentStreak: user.currentStreak,
      lastCompletedDate: user.lastCompletedDate || null,
    },
    update,
  );

  // Update database with new streak
  const longestStreak = Math.max(newState.currentStreak, user.longestStreak);

  await ctx.db.patch(userId, {
    currentStreak: newState.currentStreak,
    lastCompletedDate: newState.lastCompletedDate,
    longestStreak,
    updatedAt: Date.now(),
  });

  console.warn("[updateUserStreak] Updated user streak:", {
    userId,
    updateType: update.type,
    newStreak: newState.currentStreak,
    longestStreak,
  });
}
